/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Compat {
  name: string
  mdnUrl: string
  description: string
  tags: Array<string>
  support: Support
}
export interface Status {
  experimental: boolean
  standardTrack: boolean
  deprecated: boolean
}
export interface Support {
  chrome: string
  chromeAndroid: string
  firefox: string
  firefoxAndroid: string
  safari: string
  safariIos: string
  edge: string
  node: string
  deno: string
}
export interface CompatBox {
  name: string
  span: Span
  compat: Compat
  filePath: string
  loc: Location
}
export declare function checkBrowserSupported(target: string, options?: Options | undefined | null): Array<CompatBox>
export interface Response {
  rawValue: string
  matchDangerString: string
  filePath: string
  astNode: AstNode
}
export declare function getDangerStringsUsage(dangerStrings: Array<string>, options?: Options | undefined | null): Array<Response>
export interface Response {
  libName: string
  memberName: string
  filePath: string
  astNode: AstNode
}
export declare function getModuleMemberUsage(npmNameVec: Array<string>, options?: Options | undefined | null): Array<Response>
export interface Target {
  chrome: string
}
export interface Options {
  pattern?: string
  ignore?: Array<string>
  cwd?: string
  concurrency?: number
}
export interface AstNode {
  span: Span
  loc: Location
}
export interface Span {
  start: number
  end: number
}
export interface Location {
  start: Position
  end: Position
}
export interface Position {
  line: number
  col: number
}
