use super::visitor::SyntaxVisitor;

pub mod addition;
pub mod addition_assignment;
pub mod assignment;
pub mod async_function;
pub mod async_generator_function;
pub mod r#await;
pub mod await_top_level;
pub mod bitwise_and;
pub mod bitwise_and_assignment;
pub mod bitwise_not;
pub mod bitwise_or;
pub mod bitwise_or_assignment;
pub mod bitwise_xor;
pub mod bitwise_xor_assignment;
pub mod class;
pub mod comma;
pub mod conditional;
pub mod decrement;
pub mod delete;
pub mod destructuring;
pub mod destructuring_computed_property_names;
pub mod destructuring_rest_in_arrays;
pub mod destructuring_rest_in_objects;
pub mod division;
pub mod division_assignment;
pub mod equality;
pub mod exponentiation;
pub mod exponentiation_assignment;
pub mod function;
pub mod function_trailing_comma;
pub mod generator_function;
pub mod generator_function_trailing_comma;
pub mod greater_than;
pub mod greater_than_or_equal;
pub mod grouping;
pub mod import;
pub mod import_meta;
pub mod import_meta_resolve;
pub mod import_options_parameter;
pub mod r#in;
pub mod increment;
pub mod inequality;
pub mod instanceof;
pub mod left_shift;
pub mod left_shift_assignment;
pub mod less_than;
pub mod less_than_or_equal;
pub mod logical_and;
pub mod logical_and_assignment;
pub mod logical_not;
pub mod logical_or;
pub mod logical_or_assignment;
pub mod multiplication;
pub mod multiplication_assignment;
pub mod new;
pub mod new_target;
pub mod null;
pub mod nullish_coalescing;
pub mod nullish_coalescing_assignment;
pub mod object_initializer;
pub mod object_initializer_computed_property_names;
pub mod object_initializer_shorthand_method_names;
pub mod object_initializer_shorthand_property_names;
pub mod object_initializer_spread_properties;
pub mod optional_chaining;
pub mod property_accessors;
pub mod r#r_super;
pub mod remainder;
pub mod remainder_assignment;
pub mod right_shift;
pub mod right_shift_assignment;
pub mod spread;
pub mod spread_spread_in_arrays;
pub mod spread_spread_in_function_calls;
pub mod spread_spread_in_object_literals;
pub mod strict_equality;
pub mod strict_inequality;
pub mod subtraction;
pub mod subtraction_assignment;
pub mod this;
pub mod r#typeof;
pub mod unary_negation;
pub mod unary_plus;
pub mod unsigned_right_shift;
pub mod unsigned_right_shift_assignment;
pub mod void;
pub mod r#yield;
pub mod yield_star;

pub fn setup_operators(v: &mut SyntaxVisitor) {
  addition_assignment::setup(v);
  addition::setup(v);
  assignment::setup(v);
  async_function::setup(v);
  async_generator_function::setup(v);
  await_top_level::setup(v);
  r#await::setup(v);
  bitwise_and_assignment::setup(v);
  bitwise_and::setup(v);
}
