
import fs from "node:fs"
import { add_compat_code_str } from "./add_compat_code_str.mjs"




const data = [
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/AggregateError.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Array.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/ArrayBuffer.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/AsyncFunction.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/AsyncGenerator.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/AsyncGeneratorFunction.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/AsyncIterator.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Atomics.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/BigInt.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/BigInt64Array.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/BigUint64Array.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Boolean.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/DataView.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Date.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Error.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/EvalError.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/FinalizationRegistry.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Float16Array.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Float32Array.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Float64Array.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Function.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Generator.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/GeneratorFunction.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Int16Array.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Int32Array.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Int8Array.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/InternalError.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Intl.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Iterator.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/JSON.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Map.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Math.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Number.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Object.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Promise.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Proxy.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/RangeError.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/ReferenceError.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Reflect.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/RegExp.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Set.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/SharedArrayBuffer.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/String.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Symbol.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/SyntaxError.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Temporal.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/TypeError.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/TypedArray.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/URIError.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Uint16Array.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Uint32Array.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Uint8Array.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/Uint8ClampedArray.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/WeakMap.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/WeakRef.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/WeakSet.json",
  "https://raw.githubusercontent.com/mdn/browser-compat-data/main/javascript/builtins/globals.json",
]

export default async function generate_builtins(params) {
  let struct = []
  let impl = []

  const name_mapper = {
    "supportedValuesOf":"supported_values_of",
    "@@match":"match_symbol",
    "@@matchAll":"match_all_symbol",
    "@@replace":"replace_symbol",
    "@@search":"search_symbol",
    "@@split":"split_symbol",
    "@@hasInstance":"has_instance_symbol",
    "@@iterator":"iterator_symbol",
    "@@species":"species_symbol",
    "@@unscopables":"unscopables_symbol",
    "@@asyncIterator":"async_iterator_symbol",
    "@@toPrimitive":"to_primitive_symbol",
    "AggregateError": "aggregate_error",
    "copyWithin":"copy_with_in",
    "findIndex":"find_index",
    "findLast":"find_last",
    "findLastIndex":"find_last_index",
    "flatMap":"flat_map",
    "fromAsync":"from_async",
    "indexOf":"index_of",
    "isArray":"is_array",
    "lastIndexOf":"last_index_of",
    "reduceRight":"reduce_right",
    "toReversed":"to_reversed",
    "toSorted":"to_sorted",
    "toSpliced":"to_spliced",
    "unshift":"un_shift",
    "ArrayBuffer":"array_buffer",
    "byteLength":"byte_length",
    "isView":"is_view",
    "maxByteLength":"max_byte_length",
    "maxByteLength_option":"max_byte_length_option",
    "toLocaleString":"to_locale_string",
    "toString":"to_string",
    "transferToFixedLength":"transfer_to_fixed_length",
    "AsyncFunction":"async_function",
    "AsyncGenerator":"async_generator",
    "AsyncGeneratorFunction":"async_generator_function",
    "AsyncIterator":"async_iterator",
    "compareExchange":"compare_exchange",
    "isLockFree":"is_lock_free",
    "waitAsync":"wait_async",
    "asIntN":"as_int_n",
    "asUintN":"as_uint_n",
    "valueOf":"value_of",
    "BigInt64Array":"big_int_64_array",
    "BigUint64Array":"big_uint_64_array",
    "DataView":"data_view",
    "sharedarraybuffer_support":"shared_array_buffer_support",
    "byteOffset":"byte_offset",
    "getBigInt64":"get_big_int_64",
    "getBigUint64":"get_big_uint_64",
    "getFloat16":"get_float_16",
    "getFloat32":"get_float_32",
    "getFloat64":"get_float_64",
    "getInt16":"get_int_16",
    "getInt32":"get_int_32",
    "getInt8":"get_int_8",
    "getUint16":"get_uint_16",
    "getUint32":"get_uint_32",
    "getUint8":"get_uint_8",
    "setBigInt64":"set_big_int_64",
    "setBigUint64":"set_big_uint_64",
    "setFloat16":"set_float_16",
    "setFloat32":"set_float_32",
    "setFloat64":"set_float_64",
    "setInt16":"set_int_16",
    "setInt32":"set_int_32",
    "setInt8":"set_int_8",
    "setUint16":"set_uint_16",
    "setUint32":"set_uint_32",
    "setUint8":"set_uint_8",
    "optional_monthIndex":"optional_month_index",
    "getDate":"get_date",
    "getDay":"get_day",
    "getFullYear":"get_full_year",
    "getHours":"get_hours",
    "getMilliseconds":"get_milliseconds",
    "getMinutes":"get_minutes",
    "getMonth":"get_month",
    "getSeconds":"get_seconds",
    "getTime":"get_time",
    "getTimezoneOffset":"get_timezone_offset",
    "getUTCDate":"get_utc_date",
    "getUTCDay":"get_utc_day",
    "getUTCFullYear":"get_utc_full_year",
    "getUTCHours":"get_utc_hours",
    "getUTCMilliseconds":"get_utc_milliseconds",
    "getUTCMinutes":"get_utc_minutes",
    "getUTCMonth":"get_utc_month",
    "getUTCSeconds":"get_utc_seconds",
    "getYear":"get_year",
    "setDate":"set_date",
    "setFullYear":"set_full_year",
    "setHours":"set_hours",
    "setMilliseconds":"set_milliseconds",
    "setMinutes":"set_minutes",
    "setMonth":"set_month",
    "setSeconds":"set_seconds",
    "setTime":"set_time",
    "setUTCDate":"set_utc_date",
    "setUTCFullYear":"set_utc_full_year",
    "setUTCHours":"set_utc_hours",
    "setUTCMilliseconds":"set_utc_milliseconds",
    "setUTCMinutes":"set_utc_minutes",
    "setUTCMonth":"set_utc_month",
    "setUTCSeconds":"set_utc_seconds",
    "setYear":"set_year",
    "toDateString":"to_date_string",
    "toGMTString":"to_gmt_string",
    "toISOString":"to_iso_string",
    "toJSON":"to_json",
    "toLocaleDateString":"to_locale_date_string",
    "toLocaleTimeString":"to_locale_time_string",
    "toTimeString":"to_time_string",
    "toUTCString":"to_utc_string",
    "columnNumber":"column_number",
    "EvalError":"eval_error",
    "FinalizationRegistry":"finalization_registry",
    "displayName":"display_name",
    "toString_revision":"to_string_revision",
    "GeneratorFunction":"generator_function",
    "InternalError":"internal_error",
    "getCanonicalLocales":"get_canonical_locales",
    "toArray":"to_array",
    "isRawJSON":"is_raw_json",
    "rawJSON":"raw_json",
    "groupBy":"group_by",
    "isFinite":"is_finite",
    "isInteger":"is_integer",
    "isNaN":"is_nan",
    "isSafeInteger":"is_safe_integer",
    "parseFloat":"parse_float",
    "parseInt":"parse_int",
    "toExponential":"to_exponential",
    "toFixed":"to_fixed",
    "toPrecision":"to_precision",
    "defineGetter":"define_getter",
    "defineProperties":"define_properties",
    "defineProperty":"define_property",
    "defineSetter":"define_setter",
    "fromEntries":"from_entries",
    "getOwnPropertyDescriptor":"get_own_property_descriptor",
    "getOwnPropertyDescriptors":"get_own_property_descriptors",
    "getOwnPropertyNames":"get_own_property_names",
    "getOwnPropertySymbols":"get_own_property_symbols",
    "getPrototypeOf":"get_prototype_of",
    "hasOwn":"has_own",
    // "hasOwnProperty":"has_own_property",
    "isExtensible":"is_extensible",
    "isFrozen":"is_frozen",
    "isPrototypeOf":"is_prototype_of",
    "isSealed":"is_sealed",
    "lookupGetter":"lookup_getter",
    "lookupSetter":"lookup_setter",
    "preventExtensions":"prevent_extensions",
    "propertyIsEnumerable":"property_is_enumerable",
    "setPrototypeOf":"set_prototype_of",
    "allSettled":"all_settled",
    "withResolvers":"with_resolvers",
    "deleteProperty":"delete_property",
    "ownKeys":"own_keys",
    "RangeError":"range_error",
    "ReferenceError":"reference_error",
    "dotAll":"dot_all",
    "hasIndices":"has_indices",
    "ignoreCase":"ignore_case",
    "lastIndex":"last_index",
    "lastMatch":"last_match",
    "lastParen":"last_paren",
    "leftContext":"left_context",
    "rightContext":"right_context",
    "unicodeSets":"unicode_sets",
    "isDisjointFrom":"is_disjoint_from",
    "isSubsetOf":"is_subset_of",
    "isSupersetOf":"is_superset_of",
    "symmetricDifference":"symmetric_difference",
    "SharedArrayBuffer":"shared_array_buffer",
    
  }

  let response_list = await Promise.all(
    data.map(x => fetch(x).then(x => x.json()))
  )

  const operators = response_list.map(x => x.javascript.builtins).reduce((acc, x) => {
    return Object.assign(acc, x)
  })

  Object.entries(operators).forEach(([key, value]) => {
    let k = name_mapper[key] ?? key.toLocaleLowerCase()
    add_compat_code_str(struct,impl,name_mapper,null,k,value);
  });

  fs.writeFileSync("../src/syntax/builtins.rs", `
use super::{compat::Compat, support::Support};

pub struct Builtins<'a>{
    ${struct.join("")}
}

pub const BUILTINS: Builtins = Builtins { 
    ${impl.join("\n")}
};
    `)
}

 