
use super::{compat::Compat, support::Support};

pub struct Statements<'a> {
  
        pub async_function: Compat<'a>,
      
        pub async_generator_function: Compat<'a>,
      
        pub block: Compat<'a>,
      
        pub r#break: Compat<'a>,
      
        pub r#class: Compat<'a>,
      
        pub r#const: Compat<'a>,
      
        pub r#continue: Compat<'a>,
      
        pub r#debugger: Compat<'a>,
      
        pub do_while: Compat<'a>,
      
        pub empty: Compat<'a>,
      
        pub r#export: Compat<'a>,
      
        pub export_default: Compat<'a>,
      
        pub export_namespace: Compat<'a>,
      
        pub r#for: Compat<'a>,
      
        pub for_await_of: Compat<'a>,
      
        pub for_in: Compat<'a>,
      
        pub for_of: Compat<'a>,
      
        pub for_of_async_iterators: Compat<'a>,
      
        pub for_of_closing_iterators: Compat<'a>,
      
        pub r#function: Compat<'a>,
      
        pub function_trailing_comma_in_parameters: Compat<'a>,
      
        pub generator_function: Compat<'a>,
      
        pub generator_function_iterator_result_object: Compat<'a>,
      
        pub generator_function_not_constructable_with_new: Compat<'a>,
      
        pub generator_function_trailing_comma_in_parameters: Compat<'a>,
      
        pub if_else: Compat<'a>,
      
        pub r#import: Compat<'a>,
      
        pub import_worker_support: Compat<'a>,
      
        pub import_import_assertions: Compat<'a>,
      
        pub import_assertions_type_css: Compat<'a>,
      
        pub import_assertions_type_json: Compat<'a>,
      
        pub import_import_attributes: Compat<'a>,
      
        pub import_attributes_type_css: Compat<'a>,
      
        pub import_attributes_type_json: Compat<'a>,
      
        pub import_service_worker_support: Compat<'a>,
      
        pub import_worklet_support: Compat<'a>,
      
        pub r#label: Compat<'a>,
      
        pub r#let: Compat<'a>,
      
        pub r#return: Compat<'a>,
      
        pub r#switch: Compat<'a>,
      
        pub r#throw: Compat<'a>,
      
        pub try_catch: Compat<'a>,
      
        pub try_catch_optional_catch_binding: Compat<'a>,
      
        pub r#var: Compat<'a>,
      
        pub r#while: Compat<'a>,
      
        pub r#with: Compat<'a>,
      
}

pub const STATEMENTS: Statements = Statements {
    
    async_function: Compat {
      name: "async_function",
      description: r##"<code>async function</code> statement"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/async_function",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-async-function-definitions",
      support: Support {
        chrome: "55",
        edge: "15",
        firefox: "52",
        ie: "false",
        node: "No",
        safari: "10.1",
      },
    },
    async_generator_function: Compat {
      name: "async_generator_function",
      description: r##"<code>async function*</code> statement"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/async_function*",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-async-generator-function-definitions",
      support: Support {
        chrome: "63",
        edge: "No",
        firefox: "55",
        ie: "false",
        node: "No",
        safari: "12",
      },
    },
    block: Compat {
      name: "block",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/block",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-block",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "11",
        node: "No",
        safari: "1",
      },
    },
    r#break: Compat {
      name: "break",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/break",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-break-statement",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "3",
        node: "No",
        safari: "1",
      },
    },
    r#class: Compat {
      name: "class",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/class",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-class-definitions",
      support: Support {
        chrome: "49",
        edge: "13",
        firefox: "45",
        ie: "false",
        node: "No",
        safari: "10.1",
      },
    },
    r#const: Compat {
      name: "const",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/const",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-let-and-const-declarations",
      support: Support {
        chrome: "21",
        edge: "12",
        firefox: "36",
        ie: "11",
        node: "No",
        safari: "5.1",
      },
    },
    r#continue: Compat {
      name: "continue",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/continue",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-continue-statement",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "3",
        node: "No",
        safari: "1",
      },
    },
    r#debugger: Compat {
      name: "debugger",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/debugger",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-debugger-statement",
      support: Support {
        chrome: "5",
        edge: "12",
        firefox: "1",
        ie: "4",
        node: "No",
        safari: "5",
      },
    },
    do_while: Compat {
      name: "do_while",
      description: r##"<code>do...while</code>"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/do...while",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-do-while-statement",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "4",
        node: "No",
        safari: "1",
      },
    },
    empty: Compat {
      name: "empty",
      description: r##"Empty statement (<code>;</code>)"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/Empty",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-empty-statement",
      support: Support {
        chrome: "3",
        edge: "12",
        firefox: "1",
        ie: "3",
        node: "No",
        safari: "5",
      },
    },
    r#export: Compat {
      name: "export",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/export",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-exports",
      support: Support {
        chrome: "61",
        edge: "16",
        firefox: "60",
        ie: "false",
        node: "No",
        safari: "10.1",
      },
    },
    export_default: Compat {
      name: "default",
      description: r##"<code>default</code> keyword with <code>export</code>"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/export",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-exports",
      support: Support {
        chrome: "61",
        edge: "16",
        firefox: "60",
        ie: "false",
        node: "No",
        safari: "10.1",
      },
    },
    export_namespace: Compat {
      name: "namespace",
      description: r##"<code>export * as namespace</code>"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/export",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-exports",
      support: Support {
        chrome: "72",
        edge: "No",
        firefox: "80",
        ie: "false",
        node: "No",
        safari: "14.1",
      },
    },
    r#for: Compat {
      name: "for",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/for",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-for-statement",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "3",
        node: "No",
        safari: "1",
      },
    },
    for_await_of: Compat {
      name: "for_await_of",
      description: r##"<code>for await...of</code>"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/for-await...of",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-for-in-and-for-of-statements",
      support: Support {
        chrome: "63",
        edge: "No",
        firefox: "57",
        ie: "false",
        node: "No",
        safari: "12",
      },
    },
    for_in: Compat {
      name: "for_in",
      description: r##"<code>for...in</code>"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/for...in",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-for-in-and-for-of-statements",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "3",
        node: "No",
        safari: "1",
      },
    },
    for_of: Compat {
      name: "for_of",
      description: r##"<code>for...of</code>"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/for...of",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-for-in-and-for-of-statements",
      support: Support {
        chrome: "38",
        edge: "12",
        firefox: "13",
        ie: "false",
        node: "No",
        safari: "7",
      },
    },
    for_of_async_iterators: Compat {
      name: "async_iterators",
      description: r##"async iterators"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "63",
        edge: "12",
        firefox: "57",
        ie: "false",
        node: "No",
        safari: "7",
      },
    },
    for_of_closing_iterators: Compat {
      name: "closing_iterators",
      description: r##"Closing iterators"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "51",
        edge: "14",
        firefox: "53",
        ie: "false",
        node: "No",
        safari: "7",
      },
    },
    r#function: Compat {
      name: "function",
      description: r##"<code>function</code> statement"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/function",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-function-definitions",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "3",
        node: "No",
        safari: "1",
      },
    },
    function_trailing_comma_in_parameters: Compat {
      name: "trailing_comma_in_parameters",
      description: r##"Trailing comma in parameters"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "58",
        edge: "14",
        firefox: "52",
        ie: "false",
        node: "No",
        safari: "10",
      },
    },
    generator_function: Compat {
      name: "generator_function",
      description: r##"<code>function*</code> statement"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/function*",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-generator-function-definitions",
      support: Support {
        chrome: "39",
        edge: "13",
        firefox: "26",
        ie: "false",
        node: "No",
        safari: "10",
      },
    },
    generator_function_iterator_result_object: Compat {
      name: "IteratorResult_object",
      description: r##"<code>IteratorResult</code> object instead of throwing"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "49",
        edge: "13",
        firefox: "29",
        ie: "false",
        node: "No",
        safari: "10",
      },
    },
    generator_function_not_constructable_with_new: Compat {
      name: "not_constructable_with_new",
      description: r##"Not constructable with <code>new</code> (ES2016)"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "50",
        edge: "13",
        firefox: "43",
        ie: "false",
        node: "No",
        safari: "10",
      },
    },
    generator_function_trailing_comma_in_parameters: Compat {
      name: "trailing_comma_in_parameters",
      description: r##"Trailing comma in parameters"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "58",
        edge: "14",
        firefox: "52",
        ie: "false",
        node: "No",
        safari: "10",
      },
    },
    if_else: Compat {
      name: "if_else",
      description: r##"<code>if...else</code>"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/if...else",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-if-statement",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "3",
        node: "No",
        safari: "1",
      },
    },
    r#import: Compat {
      name: "import",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/import",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-imports",
      support: Support {
        chrome: "61",
        edge: "16",
        firefox: "60",
        ie: "false",
        node: "No",
        safari: "10.1",
      },
    },
    import_worker_support: Compat {
      name: "worker_support",
      description: r##"Available in workers"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "80",
        edge: "No",
        firefox: "114",
        ie: "false",
        node: "No",
        safari: "15",
      },
    },
    import_import_assertions: Compat {
      name: "import_assertions",
      description: r##"Import attributes with <code>assert</code> syntax (formerly import assertions)"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "91",
        edge: "No",
        firefox: "false",
        ie: "false",
        node: "No",
        safari: "false",
      },
    },
    import_assertions_type_css: Compat {
      name: "type_css",
      description: r##"<code>assert {type: 'css'}</code>"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "93",
        edge: "No",
        firefox: "false",
        ie: "false",
        node: "No",
        safari: "false",
      },
    },
    import_assertions_type_json: Compat {
      name: "type_json",
      description: r##"<code>assert {type: 'json'}</code>"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "91",
        edge: "No",
        firefox: "false",
        ie: "false",
        node: "No",
        safari: "false",
      },
    },
    import_import_attributes: Compat {
      name: "import_attributes",
      description: r##"Import attributes (<code>with</code> syntax)"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "123",
        edge: "No",
        firefox: "false",
        ie: "false",
        node: "No",
        safari: "17.2",
      },
    },
    import_attributes_type_css: Compat {
      name: "type_css",
      description: r##"<code>with {type: 'css'}</code>"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "123",
        edge: "No",
        firefox: "false",
        ie: "false",
        node: "No",
        safari: "false",
      },
    },
    import_attributes_type_json: Compat {
      name: "type_json",
      description: r##"<code>with {type: 'json'}</code>"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "123",
        edge: "No",
        firefox: "false",
        ie: "false",
        node: "No",
        safari: "17.2",
      },
    },
    import_service_worker_support: Compat {
      name: "service_worker_support",
      description: r##"Available in service workers"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "91",
        edge: "No",
        firefox: "false",
        ie: "false",
        node: "No",
        safari: "15",
      },
    },
    import_worklet_support: Compat {
      name: "worklet_support",
      description: r##"Available in worklets"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "false",
        edge: "No",
        firefox: "114",
        ie: "false",
        node: "No",
        safari: "false",
      },
    },
    r#label: Compat {
      name: "label",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/label",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-labelled-statements",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "4",
        node: "No",
        safari: "1",
      },
    },
    r#let: Compat {
      name: "let",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/let",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-let-and-const-declarations",
      support: Support {
        chrome: "49",
        edge: "14",
        firefox: "44",
        ie: "11",
        node: "No",
        safari: "10",
      },
    },
    r#return: Compat {
      name: "return",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/return",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-return-statement",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "3",
        node: "No",
        safari: "1",
      },
    },
    r#switch: Compat {
      name: "switch",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/switch",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-switch-statement",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "4",
        node: "No",
        safari: "1",
      },
    },
    r#throw: Compat {
      name: "throw",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/throw",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-throw-statement",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "5",
        node: "No",
        safari: "1",
      },
    },
    try_catch: Compat {
      name: "try_catch",
      description: r##"<code>try...catch</code>"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/try...catch",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-try-statement",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "5",
        node: "No",
        safari: "1",
      },
    },
    try_catch_optional_catch_binding: Compat {
      name: "optional_catch_binding",
      description: r##"Optional catch binding"##,
      mdn_url: "undefined",
      spec_url: "undefined",
      support: Support {
        chrome: "66",
        edge: "No",
        firefox: "58",
        ie: "false",
        node: "No",
        safari: "11.1",
      },
    },
    r#var: Compat {
      name: "var",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/var",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-variable-statement",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "3",
        node: "No",
        safari: "1",
      },
    },
    r#while: Compat {
      name: "while",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/while",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-while-statement",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "3",
        node: "No",
        safari: "1",
      },
    },
    r#with: Compat {
      name: "with",
      description: r##"undefined"##,
      mdn_url: "https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/with",
      spec_url: "https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-with-statement",
      support: Support {
        chrome: "1",
        edge: "12",
        firefox: "1",
        ie: "3",
        node: "No",
        safari: "1",
      },
    },
};