[package]
edition = "2024"
name    = "check_cloc"
version = "0.1.0"

[dependencies]
anyhow      = { workspace = true }
napi        = { workspace = true }
napi-derive = { workspace = true }
serde       = { workspace = true }
tokei       = { workspace = true }
utils       = { path = "../utils" }
